### ISSUE TITLE
CVD - Alarm Volume

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#110]
SR-25 Alarm Volume shall be 60 to 80 dBA at one meter (+/- 5 dBA).
Download the “decibel X” app. Place a phone 1 meter from ventilator. Measure a baseline decibel output. 
Trigger an alarm and record the output. 
Goal: 60 to 80 dBa at one meter

**Comment by sglow** [comment]
OK, I just tested this on the controller using the buzzer on that board.

Here's a screen shot showing the buzzer going full blast in an otherwise quiet room.  I tweaked it a bit in software so now I'm getting about 70dB

![Screenshot_20200618-202534](https://user-images.githubusercontent.com/62487520/85084220-34fc7500-b1a2-11ea-82f7-df46ecb96ecc.png)

**Comment by sglow** [comment]
When the blower is running full blast it's already at almost 60dB.  An alarm at that point raises the din up to about 75dB
![Screenshot_20200618-203432](https://user-images.githubusercontent.com/62487520/85084635-6590de80-b1a3-11ea-8c6f-881b8a6a5d4f.png)

**Comment by sglow** [comment]
Note that these measurements were for the buzzer on the controller only.  I'm not sure if that's really the alarm for the vent since most of the alarm stuff is being handled on the GUI.  Someone who has a working GUI setup should test the volume of the alarm that the touch screen speakers produces

**Comment by esc-works** [comment]
Not perfect but I'm going to close the issue and move on. Thanks @sglow !

**Comment by esc-works** [comment]
@jkff wants to update this. @martukas maybe has some data

**Comment by inceptionev** [comment]
Got the GUI up and running and filmed the testing of the volume.  Alarm testing video here: https://youtu.be/_GUU8BG_yBc

Screenshot here: 
![image](https://user-images.githubusercontent.com/8660661/85214872-c34d3400-b325-11ea-93f1-dcc73349c0f9.png)

Side note: the app that CoVent asks you to download is a $5/month subscription ::blech::

**Comment by jkff** [comment]
Section "SR-25 Alarm Volume shall be 60 to 80 dBA at one meter (+/- 5 dBA)" in Performance Evaluation Report now covers this.
