### ISSUE TITLE
CVD - Pressure Compatibility Testing

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#116]
Hook up ventilator to regulator with >50 psi supply pressure (pretending this is hospital O2).
Take a picture.
Note that first we have to settle on a proper regulator. If we don't have it in hand then we should just submit the data sheet of the regulator.

**Comment by esc-works** [comment]
we're probably not going to get to this test since we haven't picked a regulator

**Comment by jkff** [comment]
@inceptionev plans to clarify with @dtgerson exactly what should be done here.

**Comment by dtgerson** [comment]
if I'm understanding what this is about, I would say edwin should just take a picture of his ox tank with the reg hooked up to the system (ideally in a way that shows the pressure of the ox tank) and then we can post that and say we're making progress

**Comment by inceptionev** [comment]
there is a video and test data for pressure compatibility now here: https://github.com/RespiraWorks/VentilatorSoftware/tree/inceptionev/20200621-OxygenPressureCompatibilityTest/sample-data/20200621-OxygenPressureCompatibilityTest

**Comment by inceptionev** [comment]
^ the above runs test #6 with pressure from 100psi down to 20psi

**Comment by inceptionev** [comment]
we still need someone to do the write-up
