### ISSUE TITLE
CVD - Alarm: Mandatory Ventilation Turned Off

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#118]
SR-01 Operation shall support mandatory Ventilation

Turn the ventilator a “standby mode” to alert the user that the ventilator is no longer providing support to the patient (example alarm from the LTV-1200 ventilator):

**Comment by esc-works** [comment]
This should be referring to when the ventilator is turned to a “standby mode” to alert the user that the ventilator is no longer providing support to the patient (example alarm from the LTV-1200 ventilator).

![Image from iOS (17)](https://user-images.githubusercontent.com/62855852/85212161-d8659b00-b304-11ea-883e-168ea80a6227.jpg)

**Comment by jkff** [comment]
I have filled in the respective section of Performance Evaluation Report.
