### ISSUE TITLE
CVD - Oxygen Peak Flow Rate

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#119]
**Verification for**

- SR-07: Flow Rate Shall > 60L/min and
- SR-26: Actual Value (TV, RR, PEEP, FiO2, Flow Rate, PIP) shall be monitored.

**Approximate Test Procedure**

1.  Set up ventilator for normal patient delivery, with flow meter in line.
2. Turn on ventilator
3. Set required input parameters, likely a high lung compliance (C50) and low resistance (R5), as well as a relatively high respiratory rate. 
4. Set the ventilator to deliver 100% FiO2.
5. record the ventilator set parameters.
6. Provide several breaths of ventilation, record the maximum flow rate displayed on the flow meter
7. If time allows, repeat steps 3-5 for various combinations of the required input parameters trying to reach a higher flow rate.

**Comment by esc-works** [comment]
Note that it should be possible to get most of this data from the data acquired for #151

**Comment by inceptionev** [comment]
Peak oxygen flow data, video, and photos are in https://github.com/RespiraWorks/VentilatorSoftware/tree/inceptionev/20200621-Peak-Oxygen-Flow-Run-for-Record/sample-data/2020-06-21-Peak-Oxygen-Flow
