### ISSUE TITLE
CVD - System, Hardware and Software Requirements

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#124]
Export the RW-SYS requirements from Valispace

**Comment by neelfirst** [comment]
[rw-sys-reqs-2020-06-12-nks.pdf](https://github.com/RespiraWorks/SystemDesign/files/4774147/rw-sys-reqs-2020-06-12-nks.pdf)

**Comment by neelfirst** [comment]
@esc-works a quick review if you please. moving to hw/sw reqs next.

**Comment by esc-works** [comment]
This looks good to me!

**Comment by neelfirst** [comment]
[rw-hw-reqs-2020-06-16-nks.pdf](https://github.com/RespiraWorks/SystemDesign/files/4790435/rw-hw-reqs-2020-06-16-nks.pdf)

**Comment by neelfirst** [comment]
@esc-works @dtgerson @paulgun89 hardware requirements up, review requested

**Comment by neelfirst** [comment]
note I've hidden the dependencies here, but you can view them in valispace and/or the matrix i'm on the hook for later.

**Comment by neelfirst** [comment]
The more I work on these the more I realize we will need to do some serious upkeep post-covent. On my list to find some dedicated requirements engineers.

**Comment by neelfirst** [comment]
I'm updating the SW reqs a bit and finding more and more that we need to overhaul all of our subsystem requirements. The system requirements are the most presentable, of course, but I don't think I can bring the HW/SW reqs up to the same level on time.

**Comment by neelfirst** [comment]
Submitted: https://drive.google.com/file/d/1pktSzkpa1WcbzBCZT6jgiz5fpdssPRS3/view?usp=sharing
