### ISSUE TITLE
CVD - Final Presentation

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#125]
Powerpoint presentation - shared screen 
https://docs.google.com/presentation/d/1Cxhz4zI8j2c75ZaJbOaxeRyHHQKpk2q0oElNwI55kms/edit#slide=id.p

Hardware design overview
Pneumatic design overview
Software architecture document?
Hardware available - Edwin/Steve/Martin on standby with hardware

**Comment by neelfirst** [comment]
Do we have to go through slides? e.g. for UI presentation it would be way easier to use this:
https://xd.adobe.com/view/5816839b-fd33-41f2-5a21-4b218fb9867f-2e27/grid

**Comment by neelfirst** [comment]
When is our presentation, and how long is our slot?
