### ISSUE TITLE
CVD - Complete Bill of Materials (BOM)

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#127]

**Comment by neelfirst** [comment]
Current WIP: https://drive.google.com/drive/folders/1eVs0cY9wlwXcK8Br0dq63HlMA4aH8Gkt

All subassemblies complete and accounted for except enclosure and related parts.

Some pricing information missing as well.

**Comment by esc-works** [comment]
added to submission folder
