### ISSUE TITLE
CVD - Hazard Analysis Risk Assessment

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#131]
Clean up and upload the hazard analysis / risk assessment. 

**File Name:** 01-7 Hazard Analysis Risk Assessment.pdf
**Content:** This document provides our initial hazard assessment and mitigation pathways. It is a pared down version of ISO-14971 and has been used to guide our design process.

**Comment by neelfirst** [comment]
Jam is chipping away at this one: https://docs.google.com/spreadsheets/d/1qlTV5HqxnhlJXuhbSsEIfU-YwnN6PzgASv9_2dc5-cM/edit#gid=929514620

**Comment by jaimeenk-mdt** [comment]
First pass complete
[01-07 Hazard Analysis Risk Assessment.pdf](https://github.com/RespiraWorks/SystemDesign/files/4808596/01-07.Hazard.Analysis.Risk.Assessment.pdf)

**Comment by esc-works** [comment]
I don't think we're going to get a pass at this, and I've uploaded the pdf.
