### ISSUE TITLE
CVD - Design Overview Document

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#132]
https://docs.google.com/document/d/1f25ZzRwD1yrdJ6FBjPcDkkSqIT3oqhLIuNQ0xxMXOR0/edit

**Comment by esc-works** [comment]
@inceptionev update the electrical section if you have time. otherwise just needs proof reading

**Comment by jkff** [comment]
Adding myself to update the GUI section.

**Comment by esc-works** [comment]
Before closing, make sure to update the table of contents.
