### ISSUE TITLE
CoVent Requirements Traceability Matrix

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#139]
Export child relationship from valispace to show CoVent 19 requirements and how they map to the requirements in 01 - System Requirements RespiraWorks
Export of excel document

**File Name:** 01-6 Requirements Traceability Matrix
**Content:This document provides traceability between the 36 requirements in Covent and the requirements identified by RespiraWorks.**

**Comment by neelfirst** [comment]
This is weird. An RTM needs a complete test plan with test cases ("Verifications", in Valispace).

This does not correspond to a SR <-> RW-SYS mapping.

**Comment by neelfirst** [comment]
Interpreting this as just Covent SR <-> RW-SYS, this is handled in the following file:
https://drive.google.com/file/d/1pktSzkpa1WcbzBCZT6jgiz5fpdssPRS3/view?usp=sharing
