### ISSUE TITLE
CVD - Assist Control Breath Delivery

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#142]
**SR-05 Pressure Support** "Pressure Support 10-15+/-5 cmH2O; may be either flow- or pressure-triggered (Secondary function / design goal)"

I interpret this as being to have a move where we provide pressure assist control. Because this is a secondary function or design goal it is not "strictly required."

The sub-elements here of the verification process are:
1. Provide a listing of our system, hardware, and software requirements associated with pressure assist control.
2. if we can, then demonstrate verification of all of the above requirements. 
3. If not, then a more limited set, presumably something to indicate that we can provide a breath in 100ms after detecting an inspiratory effort. 
4. We should also provide documentation that pressure assist control is provided as a feature in the UI.

**Comment by esc-works** [comment]
Clarified this issue above as being about assist control, and added a new ticket for pressure support. 

It looks like this ticket testing is more or less complete as of today. Ideal data would be a waveform showing the inspiratory effort, and then the delivered breath. In the interim I will use this youtube video: https://www.youtube.com/watch?v=PXKGaeBhqVI&feature=youtu.be

**Comment by inceptionev** [comment]
Breath Detection Walkthrough is up: https://www.youtube.com/watch?v=6vUZYqXCQ2s  Data, video, and photos are here: https://github.com/RespiraWorks/VentilatorSoftware/tree/2020-06-21-BreathDetectionWalkthrough/sample-data/2020-06-21-BreathDetectionWalkthrough

**Comment by jkff** [comment]
This all appears to be currently documented under https://docs.google.com/document/d/1g7qLD5qD4BKfR1mcGq7-QY6XE2C9oIIw5GJdUzU31Zg/edit#heading=h.pt7ef8fp4ywf.

**Comment by jkff** [comment]
Is there anything more remaining on this issue or should we mark it done?
