### ISSUE TITLE
CVD - Assembly Video

### ISSUE THREAD

**Issue by paulgun89** [RespiraWorks/SystemDesign#144]
A video displaying the complete assembly of the RespiraWorks ventilator.

**Comment by esc-works** [comment]
@martukas uploaded videos here:
https://drive.google.com/drive/folders/1-8BtT_H7nck04YnaXO9_508No4qICPxw
@tijanim will record his video today

**Comment by esc-works** [comment]
@ebhillstrom is going to be editing this, adding in the video from @tijanim
