### ISSUE TITLE
CVD - PEEP testing

### ISSUE THREAD

**Issue by esc-works** [RespiraWorks/SystemDesign#152]
**Verification for**

SR-08: PEEP Pressure: 5-15 cmH2O in increments of 5 cmH20 (+/-5 cmH2O)

**Approximate Testing Procedure** 
1. Set up testing configuration (connect pressure sensor to the ventilator output, just before entry into the test lung)
2. Start pressure data logging
3. Turn on the ventilator
4. Set the desired PEEP
5. Run ventilator for data collection duration
6. Repeat steps 4-5 for each PEEP setting (5, 10, 15, 20)
7. Turn off ventilator
8. Stop data logging

**Comment by esc-works** [comment]
Note that it should be possible to get most of this data from the data acquired for #151

**Comment by esc-works** [comment]
Note @inceptionev, we will not get testing for PEEP of 15 and PEEP of 20 from the table, so recording a run there would be good.

**Comment by esc-works** [comment]
Technically only PEEP 15 is required

**Comment by inceptionev** [comment]
PEEP control test data, video, and photos are up: https://github.com/RespiraWorks/VentilatorSoftware/tree/inceptionev/20200621-PEEP-Control-Data/sample-data/20200621-PEEP-Control-Data

**Comment by esc-works** [comment]
Written up, looks good
